#!/usr/bin/env bash
SCRIPT_PATH="$(
  cd "$(dirname "$0")" || exit
  pwd -P
)"
MAGNETO_PATH="$SCRIPT_PATH/../magneto"

rm -rf repo/

function helm() {
  docker run -it --rm -a STDOUT \
    -w "/clv" \
    -v "$SCRIPT_PATH:/clv" \
    --entrypoint "helm" \
    alpine/helm "$@"
}

for d in "$SCRIPT_PATH"/src/*/; do
  chart_name=$(basename "$d")
  helm lint "src/$chart_name"
  echo "PACKAGING src/$chart_name"
  helm package "src/$chart_name" -d repo
  echo "-------------------------------------"
done

echo "Indexing charts"
helm repo index repo --url https://clouve.github.io/charts/repo/

echo "Generating README.md"
echo "# Clouve Charts" > README.md
echo "" >> README.md

yq '.entries | to_entries | .[] | "- " + .key + " " + .value.[].version' "$SCRIPT_PATH/repo/index.yaml" >> README.md

CHARTS=$(yq e -o=j -I=0 '.entries | to_entries | .[] | .key + "," + .value.[].version + "," + .value.[].appVersion' "$SCRIPT_PATH/repo/index.yaml")
for CHART in $CHARTS
do
  IFS=',' read -ra CHART_ARR <<< "${CHART//\"/}"
  chart_name="${CHART_ARR[0]}"
  chart_version="${CHART_ARR[1]}"
  chart_appVersion="${CHART_ARR[2]}"
  echo "PROCESSING $chart_name [version: $chart_version, appVersion: $chart_appVersion]"
  find "$MAGNETO_PATH/self-service/templates/$chart_name" -name "*.json.tmpl" \
    -exec sed -i'.temp' -e "s/{{chart-version}}/${chart_version}/g; s/{{chart-appVersion}}/${chart_appVersion}/g" {} +
  find "$MAGNETO_PATH/self-service/templates/$chart_name" -name "*.json.tmpl" \
    -exec sh -c 'cp "$1" "${1%.json.tmpl}.json"' _ {} \;
  find "$MAGNETO_PATH/self-service/templates/$chart_name" -name "*.json.tmpl.temp" \
    -exec sh -c 'mv "$1" "${1%.json.tmpl.temp}.json.tmpl"' _ {} \;
done
