#!/usr/bin/env bash
SCRIPT_PATH="$(
  cd "$(dirname "$0")" || exit
  pwd -P
)"

function pack() {
  charts_dir=$1
  for d in "$SCRIPT_PATH/$charts_dir"/*/; do
    chart_name=$(basename "$d")
    helm lint "$charts_dir/$chart_name"
    echo "PACKAGING $charts_dir/$chart_name"
    helm package "$charts_dir/$chart_name" -d repo
    echo "-------------------------------------"
  done
}

pack "lib"
pack "src"

echo "Indexing charts"
helm repo index repo --url "/repo/"

BUILD_ID=$(yq '.generated' "$SCRIPT_PATH/repo/index.yaml")

echo "Generating README.md"
echo "# Clouve's Charts (Build ID: $BUILD_ID)" > README.md
echo "" >> README.md

yq '.entries | to_entries | .[] | .value | .[] | "- [" + .name + " " + .version + "]("+ .urls[0] +")"' "$SCRIPT_PATH/repo/index.yaml" >> README.md
