#!/usr/bin/env bash
SCRIPT_PATH="$(
  cd "$(dirname "$0")" || exit
  pwd -P
)"
TIMESTAMP=$(date +"%Y-%m-%d-%H-%M-%S")

for d in "$SCRIPT_PATH"/src/*/; do
  chart_name=$(basename "$d")
  helm lint "src/$chart_name"
  echo "PACKAGING src/$chart_name"
  helm package "src/$chart_name" -d repo
  echo "-------------------------------------"
done

echo "Indexing charts"
helm repo index repo --url "/repo/"

echo "Generating README.md"
echo "# Clouve's Charts (Build ID: $TIMESTAMP)" > README.md
echo "" >> README.md

yq '.entries | to_entries | .[] | .value | .[] | "- [" + .name + " " + .version + "]("+ .urls[0] +")"' "$SCRIPT_PATH/repo/index.yaml" >> README.md
