#!/usr/bin/env bash
SCRIPT_PATH="$(
  cd "$(dirname "$0")" || exit
  pwd -P
)"

for d in "$SCRIPT_PATH"/lib/*/; do
  CHART_NAME=$(basename "$d")
  echo "PROCESSING CHART: $CHART_NAME"
  find "$SCRIPT_PATH"/lib/"$CHART_NAME" -type f -exec "$SCRIPT_PATH/process_file" $CHART_NAME {} \;
done
