#!/usr/bin/env bash
IFS=$'\n'
CHART_NAME="$1"
FILE_PATH="$2"
PATTERN="$CHART_NAME-password"
REPLACEMENT="clouve-password"
PREVIOUS_LINE_REPLACEMENT="name: {{ include \"$CHART_NAME.secretName\" . }}"

if grep -q "$PATTERN" "$FILE_PATH"; then
  echo "REPLACING [$PATTERN] WITH [$REPLACEMENT] -> $FILE_PATH"

  #Reading content of file into an array
  FILE_LINES=()
  while IFS= read -r line
  do
    FILE_LINES+=("$line")
  done < "$FILE_PATH"

  #Replacing the pattern with the replacement
  UPDATED_FILE_LINES=()
  TEMP_FILE_PATH="$FILE_PATH.tmp"
  for i in "${!FILE_LINES[@]}"; do
    if [[ "${FILE_LINES[$i]}" == *"$PATTERN"* ]]; then
      UPDATED_FILE_LINES[$i]=$(echo "${FILE_LINES[$i]}" | sed "s;$PATTERN;$REPLACEMENT;g")
      if [[ "${FILE_LINES[$i]}" == *"key: $PATTERN"* && "${FILE_LINES[$i-1]}" == *"name: "* ]]; then
        UPDATED_FILE_LINES[$i-1]=$(echo "${FILE_LINES[$i-1]}" | sed -e "s;name: .*$;$PREVIOUS_LINE_REPLACEMENT;g")
      fi
    else
      UPDATED_FILE_LINES[$i]="${FILE_LINES[$i]}"
    fi
  done

  #Writing the updated content to the file
  mv "$FILE_PATH" "$TEMP_FILE_PATH"
  printf "%s\n" "${UPDATED_FILE_LINES[@]}" > $FILE_PATH
  rm "$TEMP_FILE_PATH"
fi

