#!/usr/bin/env bash
SCRIPT_PATH="$(
  cd "$(dirname "$0")" || exit
  pwd -P
)"

helm repo add --force-update requarks https://charts.js.wiki
helm repo add --force-update bitnami https://charts.bitnami.com/bitnami

CLOUVE_CHARTS=(
  "bitnami/drupal" \
  "bitnami/ghost" \
  "bitnami/joomla" \
  "bitnami/mediawiki" \
  "bitnami/moodle" \
  "bitnami/odoo" \
  "bitnami/suitecrm" \
  "requarks/wiki" \
  "bitnami/wordpress"
)

rm -rf "$SCRIPT_PATH/lib/"

for chart in "${CLOUVE_CHARTS[@]}"; do
  echo "PULLING $chart chart"
  helm pull "$chart" -d lib --untar
done
