#!/usr/bin/env bash
SCRIPT_PATH="$(
  cd "$(dirname "$0")" || exit
  pwd -P
)"

CLOUVE_CHARTS=(
  "oci://registry-1.docker.io/bitnamicharts/dokuwiki" \
  "oci://registry-1.docker.io/bitnamicharts/drupal" \
  "oci://registry-1.docker.io/bitnamicharts/ghost" \
  "oci://registry-1.docker.io/bitnamicharts/joomla" \
  "oci://registry-1.docker.io/bitnamicharts/mediawiki" \
  "oci://registry-1.docker.io/bitnamicharts/moodle" \
  "oci://registry-1.docker.io/bitnamicharts/odoo" \
  "oci://registry-1.docker.io/bitnamicharts/osclass" \
  "oci://registry-1.docker.io/bitnamicharts/suitecrm" \
  "oci://registry-1.docker.io/bitnamicharts/wordpress"
)

rm -rf "$SCRIPT_PATH/src/"
rm -rf "$SCRIPT_PATH/.helm"

function helm() {
  docker run -it --rm -a STDOUT \
    -w "/clv" \
    -v "$SCRIPT_PATH:/clv" \
    -v "$SCRIPT_PATH/.helm/.config:/root/.config" \
    -v "$SCRIPT_PATH/.helm:/root" \
    --entrypoint "helm" \
    alpine/helm "$@"
}

for chart in "${CLOUVE_CHARTS[@]}"; do
  echo "PULLING $chart chart"
  helm pull "$chart" -d src --untar
done

for d in "$SCRIPT_PATH"/src/*/; do
  chart_name=$(basename "$d")
  CONFIG_REPLACE="$chart_name-password"
  CONFIG_REPLACEMENT="clouve-password"
  IFS=',' read -ra CONFIG_REPLACE_ARR <<< "$CONFIG_REPLACE"
  IFS=',' read -ra CONFIG_REPLACEMENT_ARR <<< "$CONFIG_REPLACEMENT"
  echo "PROCESSING $chart_name"
  for i in "${!CONFIG_REPLACE_ARR[@]}"
  do
    if [[ -n "${CONFIG_REPLACE_ARR[i]}" && -n "${CONFIG_REPLACEMENT_ARR[i]}" ]]; then
      echo "REPLACING [${CONFIG_REPLACE_ARR[i]}] WITH [${CONFIG_REPLACEMENT_ARR[i]}]"
      find "$SCRIPT_PATH"/src/"$chart_name" -type f -not -path "*/\.*" -exec sed -i "" -e "s;${CONFIG_REPLACE_ARR[i]};${CONFIG_REPLACEMENT_ARR[i]};g" {} +
    fi
  done
done
